# Generated by Django 4.2.7 on 2023-12-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('transactions', '0005_moneytransfer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneytransfer',
            name='account_no',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='user',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='accounts.userbankaccount'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_sent', to='accounts.userbankaccount'),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
