# Generated by Django 4.2.7 on 2023-12-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_moneytransfer_account_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyTransfer',
        ),
    ]
